"use client"

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React, {useState} from "react";
import AppContext from "@/context/AppContext";
import {inter} from './ui/fonts'

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {

  const [contexto, setContexto] = useState(false)
  const [nome, setNome] = useState('Kelvin')


  return (
    <AppContext.Provider value={[contexto, setContexto, nome]}>
      <html lang="en">
        <body
          className={`${inter.className } antialiased`}
        >
          {children}
        </body>
      </html>
    </AppContext.Provider>

  );
}
